name: 发布插件
title: "Plugin: {name}"
description: 发布插件到 Muicebot 索引库
labels: ["Plugin"]
body:
  - type: input
    id: name
    attributes:
      label: 插件名
      description: 插件纯英文名称
      placeholder: e.g. picstatus
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: 插件描述
      description: 插件描述
      placeholder: 'e.g. 基于 nonebot_plugin_htmlrender 的 Muicebot 状态插件'
    validations:
      required: true

  - type: input
    id: module
    attributes:
      label: 插件模块名
      description: 插件模块名(必须是可导入的)
      placeholder: e.g. muicebot_plugin_status
    validations:
      required: true

  - type: input
    id: repo
    attributes:
      label: 项目链接
      description: Github 项目链接
      placeholder: 'eg. https://github.com/MuikaAI/Muicebot-Plugin-Status'
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: 插件配置
      description: .env 插件配置项(注意请不要泄露关键的密钥信息而是构造一个虚拟的)
      render: dotenv
      placeholder: |
        eg.
        memory_rag_api_key=sk-11eb3f07fd824ef69845ae8752a0b18r
    validations:
      required: false